import metodos_derivada

def printar(x, delta):
    print( 26 * '=')
    print("Derivadas foward")
    print( 26 * '=')
    print("Derivada Foward de primeira ordem: ", end = "")
    print(metodos_derivada.derivada_foward(x,delta))
    print("Derivada Foward de primeira ordem (com erro O(delta²)): ", end = "")
    print(metodos_derivada.derivada_foward_erroO2(x,delta))
    print("Derivada Foward de primeira ordem (com erro O(delta³)): ", end = "")
    print(metodos_derivada.derivada_foward_erroO3(x,delta))
    print("Derivada Foward de segunda ordem: ", end = "")
    print(metodos_derivada.derivada_foward_segundaOrdem(x,delta))
    print("Derivada Foward de terceira ordem: ", end = "")
    print(metodos_derivada.derivada_foward_terceiraOrdem(x,delta))

    print( 26 * '=')
    print("Derivadas Backward")
    print( 26 * '=')
    print("Derivada Backward de primeira ordem: ", end = "")
    print(metodos_derivada.derivada_backward(x,delta))
    print("Derivada Backward de primeira ordem (com erro O(delta²)): ", end = "")
    print(metodos_derivada.derivada_backward_erroO2(x,delta))
    print("Derivada Backward de primeira ordem (com erro O(delta³)): ", end = "")
    print(metodos_derivada.derivada_backward_erroO3(x,delta))
    print("Derivada Backward de segunda ordem: ", end = "")
    print(metodos_derivada.derivada_backward_segundaOrdem(x,delta))
    
    print(27 * '=')
    print("Derivadas Central")
    print(27 * '=')
    print("Derivada Central de primeira ordem (com erro O(delta²)): ", end = "")
    print(metodos_derivada.derivada_central_erroO2(x,delta))
    print("Derivada Central de primeira ordem (com erro O(delta³)): ", end = "")
    print(metodos_derivada.derivada_central_erroO3(x,delta))
    print("Derivada Central de segunda ordem: ", end = "")
    print(metodos_derivada.derivada_central_segundaOrdem(x,delta))

def printar_foward(x,delta):
    print( 26 * '=')
    print("Derivadas foward")
    print( 26 * '=')
    print("Derivada Foward de primeira ordem: ", end = "")
    print(metodos_derivada.derivada_foward(x,delta))
    print("Derivada Foward de primeira ordem (com erro O(delta²)): ", end = "")
    print(metodos_derivada.derivada_foward_erroO2(x,delta))
    print("Derivada Foward de primeira ordem (com erro O(delta³)): ", end = "")
    print(metodos_derivada.derivada_foward_erroO3(x,delta))
    print("Derivada Foward de segunda ordem: ", end = "")
    print(metodos_derivada.derivada_foward_segundaOrdem(x,delta))
    print("Derivada Foward de terceira ordem: ", end = "")
    print(metodos_derivada.derivada_foward_terceiraOrdem(x,delta))

def printar_backward(x,delta):
    print( 26 * '=')
    print("Derivadas Backward")
    print( 26 * '=')
    print("Derivada Backward de primeira ordem: ", end = "")
    print(metodos_derivada.derivada_backward(x,delta))
    print("Derivada Backward de primeira ordem (com erro O(delta²)): ", end = "")
    print(metodos_derivada.derivada_backward_erroO2(x,delta))
    print("Derivada Backward de primeira ordem (com erro O(delta³)): ", end = "")
    print(metodos_derivada.derivada_backward_erroO3(x,delta))
    print("Derivada Backward de segunda ordem: ", end = "")
    print(metodos_derivada.derivada_backward_segundaOrdem(x,delta))

def printar_central(x,delta):
    print(27 * '=')
    print("Derivadas Central")
    print(27 * '=')
    print("Derivada Central de primeira ordem (com erro O(delta²)): ", end = "")
    print(metodos_derivada.derivada_central_erroO2(x,delta))
    print("Derivada Central de primeira ordem (com erro O(delta³)): ", end = "")
    print(metodos_derivada.derivada_central_erroO3(x,delta))
    print("Derivada Central de segunda ordem: ", end = "")
    print(metodos_derivada.derivada_central_segundaOrdem(x,delta))